# Character prompt symbol
[character]
success_symbol = "[âœ](bold green) "     # Symbol for successful commands with green color
error_symbol = "[âœ—](bold red) " 


# Git branch and status
[git_branch]
format = "ï˜ [$branch]($style)"
style = "bold purple"

[git_status]
conflicted = "ğŸš§ "
ahead = "â‡¡${count} "
behind = "â‡£${count} "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
untracked = "âœš "
stashed = "ğŸ“¦ "
modified = "âœ "
deleted = "ğŸ—‘ "
renamed = "Â» "
format = "[$all_status$ahead_behind]($style)"
style = "bold yellow"

# Battery display (will show only if battery is below a certain threshold by default)
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "ğŸ”‹"
disabled = false  # If set to true, will hide the battery module entirely

# Programming languages
[nodejs]
format = "via ğŸŒ $version "
disabled = false

[python]
format = "via ğŸ $version "
disabled = false

# Directory path truncation
[directory]
truncation_length = 3
format = "ğŸ“‚ [$path]($style)"

[aws]
disabled = true

